name: Regular Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2-14/6 * * *" # Run everyday at 10am, 4pm, 10pm, 4am

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run SimpleScraper
        run: scrapy crawl simple

      - name: Git commit and push
        uses: GuillaumeFalourd/git-commit-push@v1
        with:
          commit_message: "Regular update"
          files: config.json scrapy.log nodes/*
          force: 1
          empty: 1

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './nodes'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
